### ISSUE TITLE
Update to 0.14?

### ISSUE THREAD

**Issue by clearly** [rvdkooy/react-testutils-additions#9]
Would be great if this was upgraded to 0.14. Nice set of tools that can't be used now.

**Comment by rvdkooy** [comment]
There are lots of breaking changes, I'm looking into them this week.

R

Op 11 okt. 2015 21:33 schreef Aaron Bawcom notifications@github.com:

Would be great if this was upgraded to 0.14. Nice set of tools that can't be used now.

**Comment by rvdkooy** [comment]
Just releases version 0.2.0 on npm, which supports React V0.14

Be aware, there are breaking changes in this version!
biggest change is that React testutils returns dom elements instead of component instances.

Because we are dealing with DOM elements anyway, I decided to use [sizzle](https://www.npmjs.com/package/sizzle) behind the scene to support css selectors (react-testutils-additions now supports a lot more css selectors because of this).

Please let me know if this works.

R
